export const routes = [
  "/",
  "/blog",
  "/best-nursing-coaching-in-india",
  "/best-online-nursing-coaching",
  "/best-norcet-coaching",
  "/best-rrb-nursing-coaching",
  "/nprep-nursing-classes-review",
  "/nursing-next-live-review",
  "/genomic-nursing-review",
  "/how-to-choose-nursing-coaching",
  "/online-nursing-coaching",
  "/nursing-coaching-student-experience",
  "/best-nursing-coaching-delhi",
  "/best-nursing-coaching-jaipur",
  "/best-nursing-coaching-lucknow",
  "/best-nursing-coaching-chandigarh",
] as const;
